authors = ["Colin Caine <cmcaine@gmail.com>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GeoJSON = "61d90e0f-e114-555e-ac52-39dfb47a3ef9"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
Mux = "a975b10e-0019-58db-a62f-e48ff68538c9"
NodeJS = "2bd173c7-0d6d-553b-b6af-13a54713934c"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Query = "1a8c2f83-1ff3-5112-b086-8aa67b057ba1"
RData = "df47a6cb-8c03-5eed-afd8-b6050d6c41da"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Turf = "e89237b0-9201-11e9-31b0-6361926203f7"
VegaLite = "112f6efa-9a02-5b7d-90c0-432ed331239a"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
