name = "GCVT"
uuid = "f51cf3e6-c332-11e9-093f-fbccf24b4e7a"
authors = ["Colin Caine <cmcaine@gmail.com>"]
version = "0.1.0"

[deps]
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
Mux = "a975b10e-0019-58db-a62f-e48ff68538c9"
RData = "df47a6cb-8c03-5eed-afd8-b6050d6c41da"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
